import Foundation
import UIKit
import CoreGraphics
import CryptoKit

/// Generates a chain-of-custody PDF summarizing an incident recording session.
class IncidentSummaryService {
    // MARK: - Data Model

    struct IncidentSummary {
        let incidentID: String
        let startTime: Date
        let endTime: Date
        let duration: TimeInterval
        let locations: [LocationEntry]
        let chunkCount: Int
        let totalDataSize: Int64
        let destinations: [String]
        let contacts: [String]
        let deviceInfo: DeviceInfo
        let signingPublicKeyFingerprint: String?

        struct LocationEntry {
            let timestamp: Date
            let latitude: Double
            let longitude: Double
        }

        struct DeviceInfo {
            let name: String
            let model: String
            let osVersion: String
        }
    }

    // MARK: - PDF Generation

    /// Generates a Letter-size PDF from an incident summary.
    static func generatePDF(from summary: IncidentSummary) -> Data? {
        let pageWidth: CGFloat = 612   // Letter width in points (8.5")
        let pageHeight: CGFloat = 792  // Letter height in points (11")
        let margin: CGFloat = 50
        let contentWidth = pageWidth - margin * 2

        let renderer = UIGraphicsPDFRenderer(bounds: CGRect(x: 0, y: 0, width: pageWidth, height: pageHeight))

        let data = renderer.pdfData { context in
            context.beginPage()
            var y: CGFloat = margin

            let dateFormatter = DateFormatter()
            dateFormatter.dateStyle = .long
            dateFormatter.timeStyle = .medium
            dateFormatter.timeZone = TimeZone.current

            let durationFormatter = DateComponentsFormatter()
            durationFormatter.allowedUnits = [.hour, .minute, .second]
            durationFormatter.unitsStyle = .abbreviated

            // --- Header ---
            let titleAttrs: [NSAttributedString.Key: Any] = [
                .font: UIFont.boldSystemFont(ofSize: 22),
                .foregroundColor: UIColor.black
            ]
            let title = "INCIDENT REPORT"
            let titleStr = NSAttributedString(string: title, attributes: titleAttrs)
            titleStr.draw(at: CGPoint(x: margin, y: y))
            y += 34

            let subtitleAttrs: [NSAttributedString.Key: Any] = [
                .font: UIFont.systemFont(ofSize: 12),
                .foregroundColor: UIColor.darkGray
            ]
            let subtitle = "Generated by OnTheRecord — Evidence Survivability Platform"
            NSAttributedString(string: subtitle, attributes: subtitleAttrs).draw(at: CGPoint(x: margin, y: y))
            y += 24

            // Separator line
            let linePath = UIBezierPath()
            linePath.move(to: CGPoint(x: margin, y: y))
            linePath.addLine(to: CGPoint(x: pageWidth - margin, y: y))
            UIColor.gray.setStroke()
            linePath.lineWidth = 0.5
            linePath.stroke()
            y += 16

            // --- Incident Details ---
            y = drawSectionHeader("INCIDENT DETAILS", at: y, margin: margin)

            let bodyAttrs: [NSAttributedString.Key: Any] = [
                .font: UIFont.systemFont(ofSize: 11),
                .foregroundColor: UIColor.black
            ]
            let labelAttrs: [NSAttributedString.Key: Any] = [
                .font: UIFont.boldSystemFont(ofSize: 11),
                .foregroundColor: UIColor.black
            ]

            let details: [(String, String)] = [
                ("Incident ID:", summary.incidentID),
                ("Start Time:", dateFormatter.string(from: summary.startTime)),
                ("End Time:", dateFormatter.string(from: summary.endTime)),
                ("Duration:", durationFormatter.string(from: summary.duration) ?? "\(Int(summary.duration))s"),
                ("Chunks Recorded:", "\(summary.chunkCount)"),
                ("Total Data Size:", ByteCountFormatter.string(fromByteCount: summary.totalDataSize, countStyle: .file)),
                ("Device:", "\(summary.deviceInfo.name) (\(summary.deviceInfo.model))"),
                ("OS Version:", summary.deviceInfo.osVersion),
            ]

            for (label, value) in details {
                let labelStr = NSAttributedString(string: label, attributes: labelAttrs)
                let valueStr = NSAttributedString(string: " \(value)", attributes: bodyAttrs)
                labelStr.draw(at: CGPoint(x: margin, y: y))
                valueStr.draw(at: CGPoint(x: margin + 130, y: y))
                y += 18
            }
            y += 10

            // --- Upload Destinations ---
            if !summary.destinations.isEmpty {
                y = drawSectionHeader("UPLOAD DESTINATIONS", at: y, margin: margin)
                for dest in summary.destinations {
                    let bullet = NSAttributedString(string: "• \(dest)", attributes: bodyAttrs)
                    bullet.draw(at: CGPoint(x: margin + 10, y: y))
                    y += 16
                }
                y += 10
            }

            // --- Emergency Contacts Notified ---
            if !summary.contacts.isEmpty {
                y = drawSectionHeader("EMERGENCY CONTACTS NOTIFIED", at: y, margin: margin)
                for contact in summary.contacts {
                    let bullet = NSAttributedString(string: "• \(contact)", attributes: bodyAttrs)
                    bullet.draw(at: CGPoint(x: margin + 10, y: y))
                    y += 16
                }
                y += 10
            }

            // --- Location History ---
            if !summary.locations.isEmpty {
                y = drawSectionHeader("LOCATION HISTORY", at: y, margin: margin)

                let timeFormatter = DateFormatter()
                timeFormatter.dateFormat = "HH:mm:ss"

                let headerStr = NSAttributedString(string: "Time                Latitude         Longitude", attributes: labelAttrs)
                headerStr.draw(at: CGPoint(x: margin + 10, y: y))
                y += 16

                for entry in summary.locations.prefix(20) { // Limit to 20 entries for space
                    let row = String(format: "%@        %.6f       %.6f",
                                     timeFormatter.string(from: entry.timestamp),
                                     entry.latitude,
                                     entry.longitude)
                    NSAttributedString(string: row, attributes: bodyAttrs).draw(at: CGPoint(x: margin + 10, y: y))
                    y += 14

                    // Page break if needed
                    if y > pageHeight - 100 {
                        context.beginPage()
                        y = margin
                    }
                }
                y += 10
            }

            // --- Chain of Custody ---
            y = drawSectionHeader("CHAIN OF CUSTODY", at: y, margin: margin)
            if let fingerprint = summary.signingPublicKeyFingerprint {
                let keyLabel = NSAttributedString(string: "Signing Key Fingerprint:", attributes: labelAttrs)
                keyLabel.draw(at: CGPoint(x: margin + 10, y: y))
                y += 16
                let keyVal = NSAttributedString(string: fingerprint, attributes: [
                    .font: UIFont.monospacedSystemFont(ofSize: 10, weight: .regular),
                    .foregroundColor: UIColor.black
                ])
                keyVal.draw(at: CGPoint(x: margin + 10, y: y))
                y += 16
            }
            let custodyNote = NSAttributedString(
                string: "All video chunks are digitally signed using ECDSA P-256. Each chunk's signature covers the encrypted payload, authentication tag, metadata, and hash of the previous chunk, forming a tamper-evident chain.",
                attributes: bodyAttrs
            )
            let custodyRect = CGRect(x: margin + 10, y: y, width: contentWidth - 10, height: 60)
            custodyNote.draw(in: custodyRect)
            y += 70

            // --- Footer ---
            let footerAttrs: [NSAttributedString.Key: Any] = [
                .font: UIFont.italicSystemFont(ofSize: 9),
                .foregroundColor: UIColor.gray
            ]
            let footer = "This report was generated locally on the recording device. It is not a legal document and should be reviewed by qualified counsel."
            let footerStr = NSAttributedString(string: footer, attributes: footerAttrs)
            let footerRect = CGRect(x: margin, y: pageHeight - margin - 20, width: contentWidth, height: 30)
            footerStr.draw(in: footerRect)
        }

        return data
    }

    /// Saves a PDF to the app's documents directory and returns the URL.
    static func savePDF(_ data: Data, incidentID: String) -> URL? {
        guard let documentsDir = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask).first else {
            return nil
        }
        let fileName = "IncidentReport_\(incidentID).pdf"
        let fileURL = documentsDir.appendingPathComponent(fileName)
        do {
            try data.write(to: fileURL)
            return fileURL
        } catch {
            debugLog("[IncidentSummary] Failed to save PDF: \(error)")
            return nil
        }
    }

    /// Computes a SHA-256 fingerprint of a public key for display.
    static func fingerprint(of keyData: Data) -> String {
        let hash = SHA256.hash(data: keyData)
        return hash.compactMap { String(format: "%02X", $0) }
            .enumerated()
            .map { $0.offset > 0 && $0.offset % 4 == 0 ? " \($0.element)" : $0.element }
            .joined()
    }

    // MARK: - Private Drawing Helpers

    private static func drawSectionHeader(_ title: String, at y: CGFloat, margin: CGFloat) -> CGFloat {
        let attrs: [NSAttributedString.Key: Any] = [
            .font: UIFont.boldSystemFont(ofSize: 13),
            .foregroundColor: UIColor(red: 0.2, green: 0.2, blue: 0.4, alpha: 1.0)
        ]
        NSAttributedString(string: title, attributes: attrs).draw(at: CGPoint(x: margin, y: y))
        return y + 20
    }
}
